ALTER USER consert_user WITH SUPERUSER CREATEDB CREATEROLE;

DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'admin') THEN
    CREATE ROLE admin WITH SUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD 'admin123';
  END IF;
END
$$;

